admins/urls.py
from django.urls import path

from admins.views.main import IndexTemplateView
from admins.views.users import UserListView, UserCreateView, UserUpdateView, UserDeleteView
from admins.views.categories import CategoryListView, CategoryCreateView, CategoryUpdateView, CategoryDeleteView
from admins.views.products import ProductListView, ProductCreateView, ProductUpdateView, ProductDeleteView
from admins.views.orders import OrderListView, OrderUpdateView, OrderDeleteView, OrderCreateView

app_name = 'admins'
urlpatterns = [
    path('', IndexTemplateView.as_view(), name='index'),

    path('users/', UserListView.as_view(), name='admin_users'),
    path('users-create/', UserCreateView.as_view(), name='admin_users_create'),
    path('users-update/<int:pk>', UserUpdateView.as_view(), name='admin_users_update'),
    path('users-delete/<int:pk>', UserDeleteView.as_view(), name='admin_users_delete'),

    path('categories/', CategoryListView.as_view(), name='admin_categories'),
    path('categories-create/', CategoryCreateView.as_view(), name='admin_categories_create'),
    path('categories-update/<int:pk>', CategoryUpdateView.as_view(), name='admin_categories_update'),
    path('categories-delete/<int:pk>', CategoryDeleteView.as_view(), name='admin_categories_delete'),

    path('products/', ProductListView.as_view(), name='admin_products'),
    path('products-create/', ProductCreateView.as_view(), name='admin_products_create'),
    path('products-update/<int:pk>', ProductUpdateView.as_view(), name='admin_products_update'),
    path('products-delete/<int:pk>', ProductDeleteView.as_view(), name='admin_products_delete'),

    path('orders/', OrderListView.as_view(), name='admin_orders'),
    path('orders-create/', OrderCreateView.as_view(), name='admin_orders_create'),
    path('orders-update/<int:pk>', OrderUpdateView.as_view(), name='admin_orders_update'),
    path('orders-delete/<int:pk>', OrderDeleteView.as_view(), name='admin_orders_delete'),
]

geekshop/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

import products.views as products

handler404 = 'products.views.page_not_found'

urlpatterns = [
    path('', products.IndexTemplateView.as_view(), name='main'),
    path('products/', include('products.urls', namespace='products')),
    path('admin/', admin.site.urls),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('baskets/', include('baskets.urls', namespace='baskets')),
    path('admins/', include('admins.urls', namespace='admins')),
    path('orders/', include('ordersapp.urls', namespace='orders')),
    path('', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('debug/', include(debug_toolbar.urls))]

admins/templates/admins/includes/footer.html
<footer class="py-4 bg-light mt-auto">
    <div class="container-fluid">
        <div class="d-flex align-items-center justify-content-between small">
            <div class="text-muted">Copyright &copy; GeekShop 2023</div>
        </div>
    </div>
</footer>

admins/templates/admins/includes/side-bar.html
<div id="layoutSidenav_nav">
    <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
        <div class="sb-sidenav-menu">
            <div class="nav">
<!--                <div class="sb-sidenav-menu-heading">Приложения</div>-->
                <a class="nav-link" href="{% url 'admins:admin_users' %}">
                    <div class="sb-nav-link-icon">
                        <i class="fas fa-users"></i>
                    </div>
                    Пользователи
                </a>
                <a class="nav-link" href="{% url 'admins:admin_categories' %}">
                    <div class="sb-nav-link-icon">
                        <i class="fas fa-shopping-basket"></i>
                    </div>
                    Категории
                </a>
                <a class="nav-link" href="{% url 'admins:admin_products' %}">
                    <div class="sb-nav-link-icon">
                        <i class="fas fa-tshirt"></i>
                    </div>
                    Продукты
                </a>
                <a class="nav-link" href="{% url 'admins:admin_orders' %}">
                    <div class="sb-nav-link-icon">
                        <i class="fas fa-book"></i>
                    </div>
                    Заказы
                </a>
            </div>
        </div>
        <div class="sb-sidenav-footer"></div>
    </nav>
</div>