admins/urls.py
from django.urls import path

from admins.views.main import IndexTemplateView
from admins.views.users import UserListView, UserCreateView, UserUpdateView, UserDeleteView
from admins.views.categories import CategoryListView, CategoryCreateView, CategoryUpdateView, CategoryDeleteView
from admins.views.products import ProductListView, ProductCreateView, ProductUpdateView, ProductDeleteView
from admins.views.orders import OrderListView, OrderUpdateView, OrderDeleteView, OrderCreateView

app_name = 'admins'
urlpatterns = [
    path('', IndexTemplateView.as_view(), name='index'),

    path('users/', UserListView.as_view(), name='admin_users'),
    path('users-create/', UserCreateView.as_view(), name='admin_users_create'),
    path('users-update/<int:pk>', UserUpdateView.as_view(), name='admin_users_update'),
    path('users-delete/<int:pk>', UserDeleteView.as_view(), name='admin_users_delete'),

    path('categories/', CategoryListView.as_view(), name='admin_categories'),
    path('categories-create/', CategoryCreateView.as_view(), name='admin_categories_create'),
    path('categories-update/<int:pk>', CategoryUpdateView.as_view(), name='admin_categories_update'),
    path('categories-delete/<int:pk>', CategoryDeleteView.as_view(), name='admin_categories_delete'),

    path('products/', ProductListView.as_view(), name='admin_products'),
    path('products-create/', ProductCreateView.as_view(), name='admin_products_create'),
    path('products-update/<int:pk>', ProductUpdateView.as_view(), name='admin_products_update'),
    path('products-delete/<int:pk>', ProductDeleteView.as_view(), name='admin_products_delete'),

    path('orders/', OrderListView.as_view(), name='admin_orders'),
    path('orders-create/', OrderCreateView.as_view(), name='admin_orders_create'),
    path('orders-update/<int:pk>', OrderUpdateView.as_view(), name='admin_orders_update'),
    path('orders-delete/<int:pk>', OrderDeleteView.as_view(), name='admin_orders_delete'),
]

authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    # path('login/', authapp.UserLoginView.as_view(), name='login'),
    # path('register/', authapp.UserRegisterView.as_view(), name='register'),
    path('login/', authapp.user_login_view, name='login'),
    path('logout/', authapp.UserLogoutView.as_view(), name='logout'),
    path('register/', authapp.user_register_view, name='register'),
    path('profile/', authapp.UserDetailView.as_view(), name='profile'),
    path('change-password/', authapp.change_password, name='change-password'),

    path('login-required/', authapp.UserLoginRequired.as_view(), name='login-required'),

    path('verify/<str:email>/<str:activate_key>/', authapp.verify, name='verify'),
]

geekshop/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

import products.views as products

handler404 = 'products.views.page_not_found'

urlpatterns = [
    path('', products.IndexTemplateView.as_view(), name='main'),
    path('products/', include('products.urls', namespace='products')),
    path('admin/', admin.site.urls),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('baskets/', include('baskets.urls', namespace='baskets')),
    path('admins/', include('admins.urls', namespace='admins')),
    path('orders/', include('ordersapp.urls', namespace='orders')),
    path('', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('debug/', include(debug_toolbar.urls))]

ordersapp/urls.py
from django.urls import path

from ordersapp.views import OrderList, OrderRead, OrderDelete, order_forming_complete, \
    get_product_data, order_create

app_name = 'ordersapp'
urlpatterns = [
    path('', OrderList.as_view(), name='list'),
    path('create/', order_create, name='create'),
    path('read/<int:pk>/', OrderRead.as_view(), name='read'),
    path('delete/<int:pk>/', OrderDelete.as_view(), name='delete'),
    path('forming_complete/<int:pk>/', order_forming_complete, name='forming_complete'),
    path('product/<int:pk>/data/', get_product_data, name='product_data'),
]

products/urls.py
from django.urls import path

import products.views as products

app_name = 'products'

urlpatterns = [
    path('', products.ProductListView.as_view(), name='index'),
    path('category/<int:id_category>/', products.CategoryProductListView.as_view(), name='category'),
    path('page/<int:page>', products.ProductListView.as_view(), name='page'),
    path('product/<int:pk>/', products.ProductDetailView.as_view(), name='product'),
]

products/models.py
from django.db import models


# Create your models here.
class ProductCategory(models.Model):
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)
    is_active = models.BooleanField(verbose_name='активна', default=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=70, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)
    is_active = models.BooleanField(verbose_name='активен', default=True)

    def __str__(self):
        return f"{self.name} ({self.category.name})"

admins/views/products.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from admins.forms import ProductAdminForm
from products.mixin import AddTitleAndNavActiveToContextMixin
from products.models import Product


# Create your views here.
class ProductCreateView(CreateView, LoginRequiredMixin, AddTitleAndNavActiveToContextMixin):
    model = Product
    template_name = 'admins/admin-products-create.html'
    success_url = reverse_lazy('admins:admin_products')
    form_class = ProductAdminForm
    title = 'Админка | Создание продукта'

    login_url = '/auth/login-required'
    redirect_field_name = 'redirect_to'

    no_permission_template_name = 'admins/admin-no-permission.html'

    def get_template_names(self):
        if self.request.user.is_staff:
            return super().get_template_names()
        else:
            return self.no_permission_template_name


class ProductListView(ListView, LoginRequiredMixin, AddTitleAndNavActiveToContextMixin):
    model = Product
    template_name = 'admins/admin-products-read.html'
    title = 'Админка | Список продуктов'

    login_url = '/auth/login-required'
    redirect_field_name = 'redirect_to'

    no_permission_template_name = 'admins/admin-no-permission.html'

    def get_template_names(self):
        if self.request.user.is_staff:
            return super().get_template_names()
        else:
            return self.no_permission_template_name


class ProductUpdateView(UpdateView, LoginRequiredMixin, AddTitleAndNavActiveToContextMixin):
    model = Product
    template_name = 'admins/admin-products-update-delete.html'
    form_class = ProductAdminForm
    title = 'Админка | Обновление продукта'
    success_url = reverse_lazy('admins:admin_products')

    login_url = '/auth/login-required'
    redirect_field_name = 'redirect_to'

    no_permission_template_name = 'admins/admin-no-permission.html'

    def get_template_names(self):
        if self.request.user.is_staff:
            return super().get_template_names()
        else:
            return self.no_permission_template_name


class ProductDeleteView(DeleteView, LoginRequiredMixin, AddTitleAndNavActiveToContextMixin):
    model = Product
    success_url = reverse_lazy('admins:admin_products')

    login_url = '/auth/login-required'
    redirect_field_name = 'redirect_to'

    no_permission_template_name = 'admins/admin-no-permission.html'

    def get_template_names(self):
        if self.request.user.is_staff:
            return super().get_template_names()
        else:
            return self.no_permission_template_name

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

geekshop/products/views.py
from django.shortcuts import render
from .models import Product


# Create your views here.
def main(request):
    title = "geekshop - Главная"
    content = {'title': title}

    return render(request, 'products/index.html', content)


def products(request):
    title = 'geekshop - Каталог'
    products = Product.objects.all()
    content = {'title': title, 'products': products}

    return render(request, 'products/products.html', content)

products/views.py
from django.shortcuts import render
from django.views.generic import DetailView, ListView, TemplateView

from .mixin import AddTitleAndNavActiveToContextMixin
from .models import Product


# Create your views here.
class IndexTemplateView(TemplateView, AddTitleAndNavActiveToContextMixin):
    title = 'geekshop - Главная'
    nav_active = 'index'
    template_name = 'products/index.html'


def page_not_found(request, exception):
    return render(request, 'products/404.html', status=404)


class ProductListView(ListView, AddTitleAndNavActiveToContextMixin):
    context_object_name = 'products'
    model = Product
    template_name = 'products/products.html'
    title = 'geekshop - Каталог'
    nav_active = 'catalog'
    paginate_by = 3
    ordering = ['-id']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['id_category'] = 0
        return context


class CategoryProductListView(ListView, AddTitleAndNavActiveToContextMixin):
    context_object_name = 'products'
    model = Product
    template_name = 'products/products.html'
    title = 'geekshop - Каталог'
    nav_active = 'catalog'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        id_category = self.kwargs['id_category']
        context['id_category'] = id_category
        return context

    def get_queryset(self):
        return Product.objects. \
                   filter(category=self.kwargs['id_category'], is_active=True,
                          category__is_active=True). \
                   select_related('category')[:3]


class ProductDetailView(DetailView, AddTitleAndNavActiveToContextMixin):
    context_object_name = 'product'
    model = Product
    template_name = 'products/product.html'
    title = 'geekshop - Детальная информация'
    nav_active = 'catalog'

products/templates/products/includes/card.html
<div class="col-lg-4 col-md-6 mb-4">
    <div class="card h-100">
        <a href="{% url 'products:product' product.id %}">
            <img class="card-img-top"
                 src="{% if product.image %}{{ product.image.url }}{% endif %}"
                 alt="">
        </a>
        <div class="card-body">
            <h4 class="card-title">
                <a href="{% url 'products:product' product.id %}">{{ product.name }}</a>
            </h4>
            <h5>{{ product.price|floatformat:0 }} &#8381;</h5>
            <p class="card-text">{{ product.description }}</p>
        </div>
        <div class="card-footer text-center">
            <button type="button" class="btn btn-outline-success" value="{{ product.id  }}">
                Отправить в корзину
            </button>
        </div>
    </div>
</div>

products/templates/products/includes/menu.html
<div class="col-lg-3">
    <h1 class="my-4">GeekShop</h1>
    <div class="list-group">
        <a href="{% url 'products:index' %}"
           class="list-group-item{% if id_category == 0 %} active-category{% endif %}">
            Все категории
        </a>
        {% for category in categories %}
        {% if category.is_active %}
        <a href="{% url 'products:category' category.pk %}"
           class="list-group-item{% if category.pk == id_category %} active-category{% endif %}">
            {{ category.name }}
        </a>
        {% endif %}
        {% endfor %}
    </div>
</div>

products/templates/products/includes/navbar.html
<a class="navbar-brand" href="{% url 'main' %}">GeekShop</a>
<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive"
        aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarResponsive">
    <ul class="navbar-nav ms-auto">
        <li class="nav-item">
            <a class="nav-link{% if nav_active == 'catalog' %} active{% endif %}"
               href="{% url 'products:index' %}">Каталог <i class="fas fa-shopping-bag"></i>
            </a>
        </li>
        {% if request.user.is_authenticated or user_is_authenticated %}
        {% with authenticated=True %}
        {{ authenticated|json_script:"user-authenticated" }}
        {% endwith %}
        <li class="nav-item dropdown">
            <div class="nav-item dropdown">
                <a class="nav-link dropdown-toggle{% if nav_active == 'user' %} active{% endif %}"
                   id="navbarDropdown" data-bs-toggle="dropdown" aria-expanded="false" role="button" href=""
                   data-toggle="dropdown">
                    {{ user.username|default:'Пользователь' }}
                </a>
                <ul class="dropdown-menu">
                    <li class="dropdown-item">
                        <a class="nav-link text-dark" href="{% url 'authapp:profile' %}">
                            Профиль
                        </a>
                    </li>
                    <li class="dropdown-item">
                        <a class="nav-link text-dark" href="{% url 'orders:list' %}">
                            Заказы
                        </a>
                    </li>
                </ul>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'auth:logout' %}">Выйти
                <i class="fas fa-sign-out-alt"></i></a>
        </li>
        <li class="nav-item">
            <a class="nav-link{% if nav_active == 'basket' %} active{% endif %}" href="{% url 'baskets:main' %}">
                Корзина <i class="fas fa-shopping-cart"></i>
                <span class="badge text-bg-secondary
                        total-quantity-navigation">{{ baskets.0.total_quantity }}</span>
            </a>
        </li>
        {% else %}
        <li class="nav-item">
            <a class="nav-link" href="" data-bs-target="#login-modal" type="button" data-bs-toggle="modal">
                Войти/Зарегистрироваться
                <i class="fas fa-sign-in-alt"></i></a>
        </li>
        {% endif %}
        {% if user.is_staff %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'admins:index' %}">
                <i class="fas fa-users-cog"></i>
            </a>
        </li>
        {% endif %}
    </ul>
</div>