admins/urls.py
from django.urls import path

from admins.views.main import IndexTemplateView
from admins.views.users import UserListView, UserCreateView, UserUpdateView, UserDeleteView
from admins.views.categories import CategoryListView, CategoryCreateView, CategoryUpdateView, CategoryDeleteView
from admins.views.products import ProductListView, ProductCreateView, ProductUpdateView, ProductDeleteView
from admins.views.orders import OrderListView, OrderUpdateView, OrderDeleteView, OrderCreateView

app_name = 'admins'
urlpatterns = [
    path('', IndexTemplateView.as_view(), name='index'),

    path('users/', UserListView.as_view(), name='admin_users'),
    path('users-create/', UserCreateView.as_view(), name='admin_users_create'),
    path('users-update/<int:pk>', UserUpdateView.as_view(), name='admin_users_update'),
    path('users-delete/<int:pk>', UserDeleteView.as_view(), name='admin_users_delete'),

    path('categories/', CategoryListView.as_view(), name='admin_categories'),
    path('categories-create/', CategoryCreateView.as_view(), name='admin_categories_create'),
    path('categories-update/<int:pk>', CategoryUpdateView.as_view(), name='admin_categories_update'),
    path('categories-delete/<int:pk>', CategoryDeleteView.as_view(), name='admin_categories_delete'),

    path('products/', ProductListView.as_view(), name='admin_products'),
    path('products-create/', ProductCreateView.as_view(), name='admin_products_create'),
    path('products-update/<int:pk>', ProductUpdateView.as_view(), name='admin_products_update'),
    path('products-delete/<int:pk>', ProductDeleteView.as_view(), name='admin_products_delete'),

    path('orders/', OrderListView.as_view(), name='admin_orders'),
    path('orders-create/', OrderCreateView.as_view(), name='admin_orders_create'),
    path('orders-update/<int:pk>', OrderUpdateView.as_view(), name='admin_orders_update'),
    path('orders-delete/<int:pk>', OrderDeleteView.as_view(), name='admin_orders_delete'),
]

authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    # path('login/', authapp.UserLoginView.as_view(), name='login'),
    # path('register/', authapp.UserRegisterView.as_view(), name='register'),
    path('login/', authapp.user_login_view, name='login'),
    path('logout/', authapp.UserLogoutView.as_view(), name='logout'),
    path('register/', authapp.user_register_view, name='register'),
    path('profile/', authapp.UserDetailView.as_view(), name='profile'),
    path('change-password/', authapp.change_password, name='change-password'),

    path('login-required/', authapp.UserLoginRequired.as_view(), name='login-required'),

    path('verify/<str:email>/<str:activate_key>/', authapp.verify, name='verify'),
]

geekshop/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

import products.views as products

handler404 = 'products.views.page_not_found'

urlpatterns = [
    path('', products.IndexTemplateView.as_view(), name='main'),
    path('products/', include('products.urls', namespace='products')),
    path('admin/', admin.site.urls),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('baskets/', include('baskets.urls', namespace='baskets')),
    path('admins/', include('admins.urls', namespace='admins')),
    path('orders/', include('ordersapp.urls', namespace='orders')),
    path('', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('debug/', include(debug_toolbar.urls))]

ordersapp/models.py
from django.db import models

# Create your models here.
from django.conf import settings
from django.db import models

# Create your models here.

from products.models import Product


class OrderItemQuerySet(models.QuerySet):
    def delete(self, *args, **kwargs):
        for item in self:
            item.product.quantity += item.quantity
            item.product.save()
        super(OrderItemQuerySet, self).delete(*args, **kwargs)


class Order(models.Model):
    FORMING = 'FM'
    SEND_TO_PROCESSED = 'STP'
    PAID = 'PD'
    PROCESSED = 'PRD'
    READY = 'RDY'
    CANCEL = 'CNC'

    ORDER_STATUS_CHOICES = (
        (FORMING, 'формируется'),
        (SEND_TO_PROCESSED, 'отправлен в обработку'),
        (PAID, 'оплачен'),
        (PROCESSED, 'обрабатывается'),
        (READY, 'готов к выдачи'),
        (CANCEL, 'отмена заказа'),
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created = models.DateTimeField(verbose_name='создан', auto_now_add=True)
    updated = models.DateTimeField(verbose_name='обновлен', auto_now=True)
    paid = models.DateTimeField(verbose_name='оплачен', null=True, blank=True)
    status = models.CharField(choices=ORDER_STATUS_CHOICES, verbose_name='статус', max_length=3, default=FORMING)
    is_active = models.BooleanField(verbose_name='активный', default=True)

    def __str__(self):
        return f'Текущий заказ {self.pk}'

    def get_total_cost(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.get_product_cost(), items)))

    def get_total_quantity(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.quantity, items)))

    def get_items(self):
        pass

    def delete(self, using=None, keep_parents=False):
        for item in self.orderitems.select_related():
            item.product.quantity += item.quantity
            item.save()
        self.is_active = False
        self.save()


class OrderItem(models.Model):
    objects = OrderItemQuerySet.as_manager()

    order = models.ForeignKey(Order, verbose_name='заказ', related_name='orderitems', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, verbose_name='продукт', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name='количество', default=0)

    def get_product_cost(self):
        return self.product.price * self.quantity

    def save(self, *args, **kwargs):
        if self.pk:
            item = self.get_item(int(self.pk))
            self.product.quantity -= self.quantity - item
        else:
            self.product.quantity -= self.quantity
        self.product.save()
        super(OrderItem, self).save(*args, **kwargs)

    @staticmethod
    def get_item(pk):
        return OrderItem.objects.get(pk=pk).quantity

admins/templates/admins/admin-categories-read.html
{% extends 'admins/base.html' %}

{% block content %}
<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Категории</h1>
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fas fa-table mr-1"></i>
                    Категории
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                            <tr>
                                <th>Имя категории</th>
                                <th>Описание</th>
                                <th>Активная</th>
                            </tr>
                            </thead>

                            <tbody>
                            {% for category in object_list %}
                            {% if category.is_active %}
                            <tr>
                                {% else %}
                            <tr class="table-warning">
                                {% endif %}
                                <td><a href="{% url 'admins:admin_categories_update' category.id %}"
                                       style="color: dodgerblue">{{ category.name }}</a></td>
                                <td>{{ category.description }}</td>
                                <td class="text-center">
                                    {% if category.is_active %}
                                    <i class="fas fa-check-circle"></i>
                                    {% else %}
                                    <i class="fas fa-times-circle"></i>
                                    {% endif %}
                                </td>
                            </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="card-footer">
                    <a href="{% url 'admins:admin_categories_create' %}">
                        <button class="btn btn-success">Создать категорию</button>
                    </a>
                </div>
            </div>
        </div>
    </main>
    {% include 'admins/includes/footer.html' %}
</div>
{% endblock %}

admins/templates/admins/admin-categories-update-delete.html
{% extends 'admins/base.html' %}

{% block content %}
<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Редактирование категории | {{ productcategory.name }}</h1>
            <div class="card-body">
                <form action="{% url 'admins:admin_categories_update' productcategory.id %}" method="post"
                      enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.name.id_for_label }}">Название</label>
                                {{ form.name }}
                            </div>
                        </div>
                        <div class="col-lg-3">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.is_active.id_for_label }}">Скидка:
                                    </label>
                                {{ form.discount }}
                            </div>
                        </div>
                        <div class="col-lg-3">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.is_active.id_for_label }}">Категория
                                    активна:</label>
                                {{ form.is_active }}
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.description.id_for_label }}">Описание</label>
                                {{ form.description }}
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                        </div>
                    </div>
                </form>
                <form action="{% url 'admins:admin_categories_delete' productcategory.id %}" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </main>
    {% include 'admins/includes/footer.html' %}
</div>
{% endblock %}

admins/templates/admins/admin-no-permission.html
{% extends 'admins/base.html' %}
{% block content %}
<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Недостаточно прав для просмотра страницы</h1>
        </div>
    </main>
    {% include 'admins/includes/footer.html' %}
</div>
{% endblock %}

admins/templates/admins/admin-orders-read.html
{% extends 'admins/base.html' %}

{% block content %}
<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Заказы</h1>
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fas fa-table mr-1"></i>
                    Заказы
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                            <tr>
                                <th>Номер заказа</th>
                                <th>Пользователь</th>
                                <th>Создан</th>
                                <th>Изменен</th>
                                <th>Оплачен</th>
                                <th>Статус заказа</th>
                                <th>Активен</th>
                            </tr>
                            </thead>

                            <tbody>
                            {% for order in object_list %}
                            {% if order.is_active %}
                            <tr>
                            {% else %}
                            <tr class="table-warning">
                            {% endif %}
                                <td><a href="{% url 'admins:admin_orders_update' order.id %}"
                                       style="color: dodgerblue">{{ order.id }}</a></td>
                                <td><a href="{% url 'admins:admin_users_update' order.user.id %}"
                                       style="color: dodgerblue">{{ order.user }}</a></td>
                                <td>{{ order.created }}</td>
                                <td>{{ order.updated }}</td>
                                <td class="text-center">
                                    {% if order.paid %}
                                    {{ order.paid }}
                                    {% else %}
                                    <i class="fas fa-times-circle"></i>
                                    {% endif %}
                                </td>
                                <td>{{ order.get_status_display }}</td>
                                <td class="text-center">
                                    {% if order.is_active %}
                                    <i class="fas fa-check-circle"></i>
                                    {% else %}
                                    <i class="fas fa-times-circle"></i>
                                    {% endif %}
                                </td>
                            </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="card-footer">
                    <a href="{% url 'admins:admin_orders_create' %}">
                        <button class="btn btn-success">Создать заказ</button>
                    </a>
                </div>
            </div>
        </div>
    </main>
    {% include 'admins/includes/footer.html' %}
</div>
{% endblock %}

admins/templates/admins/admin-orders-update-delete.html
{% extends 'admins/base.html' %}

{% block content %}
<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Редактирование заказа | {{ order.id }}</h1>
            <div class="card-body order_form">
                <form action="{% url 'admins:admin_orders_update' order.id %}" method="post"
                      enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-lg-6">
                            Номер заказа: {{ order.id }}
                        </div>
                        <div class="col-lg-6">
                            Пользователь: <a href="{% url 'admins:admin_users_update' order.user.id %}"
                                             style="color: dodgerblue">{{ order.user }}</a>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-6">
                            Создан: {{ order.created }}
                        </div>
                        <div class="col-lg-6">
                            Изменен: {{ order.updated }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-6">
                            Заказ оплачен:
                            {% if order.paid %}
                            {{ order.paid }}
                            {% else %}
                            нет
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="id_status">Статус</label>
                                <select name="status" class="form-control" required id="id_status">
                                    {% for status in order.ORDER_STATUS_CHOICES %}
                                    {% if order.status == status.0 %}
                                    <option value="{{ status.0 }}" selected>{{ status.1 }}</option>
                                    {% else %}
                                    <option value="{{ status.0 }}">{{ status.1 }}</option>
                                    {% endif %}
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.is_active.id_for_label }}">Заказ
                                активен:</label>
                            {{ form.is_active }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-6">
                            общее количество товаров: <span class="order_total_quantity">
                                {{ object.get_total_quantity }}</span>
                        </div>
                        <div class="col-lg-6">
                            общая стоимость: <span class="order_total_cost">
                                {{ object.get_total_cost }}</span> руб
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                {{ orderitems.management_form }}
                                {% for form in orderitems.forms %}
                                {% if forloop.first %}
                                <thead>
                                <tr>
                                    {% for field in form.visible_fields %}
                                    <th>
                                        {{ field.label|capfirst }}
                                    </th>
                                    {% endfor %}
                                </tr>
                                </thead>
                                <tbody>
                                {% endif %}

                                <tr class="formset_row">
                                    {% for field in form.visible_fields %}
                                    <td class="formset_td">
                                        {% if forloop.first %}
                                        {% for hidden in form.hidden_fields %}
                                        {{ hidden }}
                                        {% endfor %}
                                        {% endif %}
                                        {{ field.errors.as_ul }}

                                        {% if field.name == 'image' %}
                                        {% if field.value and field.value != 'None' %}
                                        <img width="100" height="100"
                                             src="{{ field.value.url }}"
                                             class="img-thumbnail">
                                        {% endif %}
                                        {% elif field.name == 'price' %}
                                        {% if field.value %}
                                        <span class="orderitems-{{ forloop.parentloop.counter0 }}-price">
                                            {{ field.value}} руб </span>
                                        {% endif %}
                                        {% else %}
                                        {{ field }}
                                        {% endif %}
                                    </td>
                                    {% endfor %}
                                </tr>
                                {% endfor %}

                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                        </div>
                    </div>
                </form>
                <form action="{% url 'admins:admin_orders_delete' order.id %}" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </main>
    {% include 'admins/includes/footer.html' %}
</div>
{% endblock %}

admins/templates/admins/admin-products-read.html
{% extends 'admins/base.html' %}

{% block content %}
<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Продукты</h1>
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fas fa-table mr-1"></i>
                    Продукты
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                            <tr>
                                <th>Фото</th>
                                <th>Продукт</th>
                                <th>Короткое описание</th>
                                <th>Описание</th>
                                <th>Цена</th>
                                <th>Количество</th>
                                <th>Категория</th>
                                <th>Активный</th>
                            </tr>
                            </thead>

                            <tbody>
                            {% for product in object_list %}
                            {% if product.is_active %}
                            <tr>
                                {% else %}
                            <tr class="table-warning">
                                {% endif %}
                                <td>
                                    {% if product.image %}
                                    <img width="100" height="100"
                                         src="{{ product.image.url }}" class="img-thumbnail">
                                    {% endif %}
                                </td>
                                <td><a href="{% url 'admins:admin_products_update' product.id %}"
                                       style="color: dodgerblue">{{ product.name }}</a></td>
                                <td>{{ product.short_desc }}</td>
                                <td>{{ product.description }}</td>
                                <td>{{ product.price }}</td>
                                <td>{{ product.quantity }}</td>
                                <td>{{ product.category }}</td>
                                <td class="text-center">
                                    {% if product.is_active %}
                                    <i class="fas fa-check-circle"></i>
                                    {% else %}
                                    <i class="fas fa-times-circle"></i>
                                    {% endif %}
                                </td>
                            </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="card-footer">
                    <a href="{% url 'admins:admin_products_create' %}">
                        <button class="btn btn-success">Создать продукт</button>
                    </a>
                </div>
            </div>
        </div>
    </main>
    {% include 'admins/includes/footer.html' %}
</div>
{% endblock %}

admins/templates/admins/admin-products-update-delete.html
{% extends 'admins/base.html' %}

{% block content %}
<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Редактирование товара | {{ product.name }}</h1>
            <div class="card-body">
                <form action="{% url 'admins:admin_products_update' product.id %}" method="post"
                      enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-row">
                        <col-lg-6>
                            <img width="100" height="100"
                                 src="{% if product.image %}{{ product.image.url }}{% endif %}"
                                 class="img-thumbnail">
                        </col-lg-6>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-12">
                            <label class="custom-file-label" for="{{ form.image.id_for_label }}">Выберите
                                изображение</label>
                            {{ form.image }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.name.id_for_label }}">Название</label>
                                {{ form.name }}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.short_desc.id_for_label }}">Короткое
                                    описание</label>
                                {{ form.short_desc }}
                            </div>
                        </div>
                        <div class="col-lg-6">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.description.id_for_label }}">Описание</label>
                                {{ form.description }}
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.price.id_for_label }}">Цена</label>
                                {{ form.price }}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.quantity.id_for_label }}">Количество</label>
                                {{ form.quantity }}
                            </div>
                        </div>
                        <div class="col-lg-6">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.price.id_for_label }}">Категория</label>
                                {{ form.category }}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.is_active.id_for_label }}">Продукт
                                    активен:</label>
                                {{ form.is_active }}
                            </div>
                        </div>
                        <div class="col-lg-6">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                        </div>
                    </div>
                </form>
                <form action="{% url 'admins:admin_products_delete' product.id %}" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </main>
    {% include 'admins/includes/footer.html' %}
</div>
{% endblock %}

admins/templates/admins/admin.html
{% extends 'admins/base.html' %}
{% block content %}
<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Административная панель</h1>

        </div>
    </main>
    {% include 'admins/includes/footer.html' %}
</div>
{% endblock %}