admins/urls.py
from django.urls import path

from admins.views.main import IndexTemplateView
from admins.views.users import UserListView, UserCreateView, UserUpdateView, UserDeleteView
from admins.views.categories import CategoryListView, CategoryCreateView, CategoryUpdateView, CategoryDeleteView
from admins.views.products import ProductListView, ProductCreateView, ProductUpdateView, ProductDeleteView
from admins.views.orders import OrderListView, OrderUpdateView, OrderDeleteView, OrderCreateView

app_name = 'admins'
urlpatterns = [
    path('', IndexTemplateView.as_view(), name='index'),

    path('users/', UserListView.as_view(), name='admin_users'),
    path('users-create/', UserCreateView.as_view(), name='admin_users_create'),
    path('users-update/<int:pk>', UserUpdateView.as_view(), name='admin_users_update'),
    path('users-delete/<int:pk>', UserDeleteView.as_view(), name='admin_users_delete'),

    path('categories/', CategoryListView.as_view(), name='admin_categories'),
    path('categories-create/', CategoryCreateView.as_view(), name='admin_categories_create'),
    path('categories-update/<int:pk>', CategoryUpdateView.as_view(), name='admin_categories_update'),
    path('categories-delete/<int:pk>', CategoryDeleteView.as_view(), name='admin_categories_delete'),

    path('products/', ProductListView.as_view(), name='admin_products'),
    path('products-create/', ProductCreateView.as_view(), name='admin_products_create'),
    path('products-update/<int:pk>', ProductUpdateView.as_view(), name='admin_products_update'),
    path('products-delete/<int:pk>', ProductDeleteView.as_view(), name='admin_products_delete'),

    path('orders/', OrderListView.as_view(), name='admin_orders'),
    path('orders-create/', OrderCreateView.as_view(), name='admin_orders_create'),
    path('orders-update/<int:pk>', OrderUpdateView.as_view(), name='admin_orders_update'),
    path('orders-delete/<int:pk>', OrderDeleteView.as_view(), name='admin_orders_delete'),
]

geekshop/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

import products.views as products

handler404 = 'products.views.page_not_found'

urlpatterns = [
    path('', products.IndexTemplateView.as_view(), name='main'),
    path('products/', include('products.urls', namespace='products')),
    path('admin/', admin.site.urls),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('baskets/', include('baskets.urls', namespace='baskets')),
    path('admins/', include('admins.urls', namespace='admins')),
    path('orders/', include('ordersapp.urls', namespace='orders')),
    path('', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('debug/', include(debug_toolbar.urls))]

ordersapp/urls.py
from django.urls import path

from ordersapp.views import OrderList, OrderRead, OrderDelete, order_forming_complete, \
    get_product_data, order_create

app_name = 'ordersapp'
urlpatterns = [
    path('', OrderList.as_view(), name='list'),
    path('create/', order_create, name='create'),
    path('read/<int:pk>/', OrderRead.as_view(), name='read'),
    path('delete/<int:pk>/', OrderDelete.as_view(), name='delete'),
    path('forming_complete/<int:pk>/', order_forming_complete, name='forming_complete'),
    path('product/<int:pk>/data/', get_product_data, name='product_data'),
]

ordersapp/models.py
from django.db import models

# Create your models here.
from django.conf import settings
from django.db import models

# Create your models here.

from products.models import Product


class OrderItemQuerySet(models.QuerySet):
    def delete(self, *args, **kwargs):
        for item in self:
            item.product.quantity += item.quantity
            item.product.save()
        super(OrderItemQuerySet, self).delete(*args, **kwargs)


class Order(models.Model):
    FORMING = 'FM'
    SEND_TO_PROCESSED = 'STP'
    PAID = 'PD'
    PROCESSED = 'PRD'
    READY = 'RDY'
    CANCEL = 'CNC'

    ORDER_STATUS_CHOICES = (
        (FORMING, 'формируется'),
        (SEND_TO_PROCESSED, 'отправлен в обработку'),
        (PAID, 'оплачен'),
        (PROCESSED, 'обрабатывается'),
        (READY, 'готов к выдачи'),
        (CANCEL, 'отмена заказа'),
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created = models.DateTimeField(verbose_name='создан', auto_now_add=True)
    updated = models.DateTimeField(verbose_name='обновлен', auto_now=True)
    paid = models.DateTimeField(verbose_name='оплачен', null=True, blank=True)
    status = models.CharField(choices=ORDER_STATUS_CHOICES, verbose_name='статус', max_length=3, default=FORMING)
    is_active = models.BooleanField(verbose_name='активный', default=True)

    def __str__(self):
        return f'Текущий заказ {self.pk}'

    def get_total_cost(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.get_product_cost(), items)))

    def get_total_quantity(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.quantity, items)))

    def get_items(self):
        pass

    def delete(self, using=None, keep_parents=False):
        for item in self.orderitems.select_related():
            item.product.quantity += item.quantity
            item.save()
        self.is_active = False
        self.save()


class OrderItem(models.Model):
    objects = OrderItemQuerySet.as_manager()

    order = models.ForeignKey(Order, verbose_name='заказ', related_name='orderitems', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, verbose_name='продукт', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name='количество', default=0)

    def get_product_cost(self):
        return self.product.price * self.quantity

    def save(self, *args, **kwargs):
        if self.pk:
            item = self.get_item(int(self.pk))
            self.product.quantity -= self.quantity - item
        else:
            self.product.quantity -= self.quantity
        self.product.save()
        super(OrderItem, self).save(*args, **kwargs)

    @staticmethod
    def get_item(pk):
        return OrderItem.objects.get(pk=pk).quantity

ordersapp/forms.py
from django import forms
from ordersapp.models import Order, OrderItem


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        for filed_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class OrderItemsForm(forms.ModelForm):
    price = forms.CharField(label='цена', required=False)

    class Meta:
        model = OrderItem
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(OrderItemsForm, self).__init__(*args, **kwargs)
        for filed_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

ordersapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.
from django.db import transaction
from django.http import HttpResponseRedirect, JsonResponse
# Create your views here.
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, DeleteView

from baskets.models import Basket
from geekshop import settings
from ordersapp.models import Order, OrderItem
from products.mixin import AddTitleAndNavActiveToContextMixin
from products.models import Product


def is_ajax(request):
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'


class OrderList(ListView, LoginRequiredMixin, AddTitleAndNavActiveToContextMixin):
    model = Order
    title = 'GeekShop - Список заказов'
    nav_active = 'user'

    login_url = '/auth/login-required'
    redirect_field_name = 'redirect_to'

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user).order_by('-id')


@login_required
def order_create(request):
    with transaction.atomic():
        user_select = request.user

        order = Order(user=user_select)
        order.save()

        baskets = Basket.objects.filter(user=user_select)
        for basket in baskets:
            order_item = OrderItem(order=order, product=basket.product, quantity=basket.quantity)
            order_item.save()
            basket.delete()
    return HttpResponseRedirect(reverse('orders:list'))


class OrderRead(DetailView, LoginRequiredMixin, AddTitleAndNavActiveToContextMixin):
    model = Order
    title = 'GeekShop - Просмотр заказа'
    nav_active = 'user'

    login_url = '/auth/login-required'
    redirect_field_name = 'redirect_to'


class OrderDelete(DeleteView, LoginRequiredMixin, AddTitleAndNavActiveToContextMixin):
    model = Order
    success_url = reverse_lazy('orders:list')
    title = 'GeekShop - Удаление заказа'
    nav_active = 'user'

    login_url = '/auth/login-required'
    redirect_field_name = 'redirect_to'


def order_forming_complete(request, pk):
    order = Order.objects.get(pk=pk)
    order.status = Order.SEND_TO_PROCESSED
    order.save()
    return HttpResponseRedirect(reverse('orders:list'))


def get_product_data(request, pk):
    if is_ajax(request=request):
        product = Product.objects.get(pk=pk)
        if product:
            image = settings.MEDIA_URL + str(product.image)
            return JsonResponse({
                'price': product.price,
                'image': image,
            })
        return JsonResponse({'price': 0, 'image': ''})

ordersapp/templates/ordersapp/order_confirm_delete.html
{% extends 'products/base.html' %}
{% load static %}

{% block css %}
<!-- Bootstrap core CSS -->
<link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

<!-- Custom styles for this template -->
<link href="/static/css/style.css" rel="stylesheet">
{% endblock %}

{% block content %}
<!-- Page Content -->
<div class="container flex-grow-1">
    <div class="row">
        <div class="col-12">
            <h1 class="my-4">Уверены, что хотите удалить заказ?</h1>
            <div class="card">
                <div class="card-header">Заказ №{{ object.pk }} от {{ object.created|date:"d E Y H:i" }},
                    статус: {{ object.get_status_display }}
                </div>
                <div class="card-footer">
                    {{ object.get_total_quantity }} товара на сумму {{ object.get_total_cost }} руб.
                </div>
            </div>
            <form class="" action="{% url 'orders:delete' object.pk %}" method="post">
                {% csrf_token %}
                <input class="btn btn-danger btn-round form-control my-2 last" type="submit" value="удалить">
                <a href="{% url 'orders:list' %}" class="btn btn-a btn-round form-control my-2 last">отмена</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

ordersapp/templates/ordersapp/order_detail.html
{% extends "products/base.html" %}
{% load static %}

{% block css %}
<!-- Bootstrap core CSS -->
<link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

<!-- Custom styles for this template -->
<link href="/static/css/style.css" rel="stylesheet">
{% endblock %}

{% block content %}
<!-- Page Content -->
<div class="container flex-grow-1">
    <div class="row">
        <div class="col-12">
            <h1 class="my-4">Заказ №{{ object.pk }} от {{ object.created|date:"d E Y H:i" }},
                статус: {{ object.get_status_display }}</h1>
            <div class="card">
                <div class="card-header">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th></th>
                            <th>Категория</th>
                            <th>Продукт</th>
                            <th>Количество</th>
                            <th>Цена</th>
                            <th>Итого</th>
                        </tr>
                        </thead>

                        <tbody>
                        {% for item in object.orderitems.select_related %}
                        <tr>
                            <td>
                                <img style="height: 150px" src="{{ item.product.image.url }}"
                                     alt="{{ item.product.short_desc }}">
                            </td>
                            <td>{{ item.product.category.name }}</td>
                            <td>{{ item.product.name }}</td>
                            <td>{{ item.quantity }}</td>
                            <td>{{ item.product.price }}</td>
                            <td>{{ item.get_product_cost }}</td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="card-footer">
                    {{ object.get_total_quantity }} товара на сумму {{ object.get_total_cost }} руб.
                </div>
            </div>
            {% include 'ordersapp/includes/inc_order_actions.html' %}
        </div>
    </div>
</div>
{% endblock %}

ordersapp/templates/ordersapp/order_list.html
{% extends 'products/base.html' %}
{% load static %}

{% block css %}
<!-- Bootstrap core CSS -->
<link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'css/style.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<!-- Page Content -->
<div class="container flex-grow-1">
    <div class="row">
        <div class="col-12">
            <h1 class="my-4">
                Ваши заказы,
                {% if user.username %}
                {{ user.username }}
                {% else %}
                Пользователь
                {% endif %}
            </h1>
            <div class="card">
                <div class="card-header">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Создан</th>
                            <th>Обновлен</th>
                            <th>Статус</th>
                            <th>Детали заказа</th>
                            <th>Удалить</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for item in object_list %}
                        {% if item.is_active %}
                        <tr>
                            <td class="td1 orders_list">{{ item.pk }}</td>
                            <td>{{ item.created|date:"d E Y H:i" }}</td>
                            <td>{{ item.updated|date:"d E Y H:i" }}</td>
                            <td>{{ item.get_status_display }}</td>
                            <td>
                                <a href="{% url 'orders:read' item.pk %}">
                                    Посмотреть детали заказа
                                </a>
                            </td>
                            <td class="text-center">
                                {% if item.status == 'FM' %}
                                <a href="{% url 'orders:delete' item.pk %}">
                                    <i class="fas fa-trash text-danger" aria-hidden="true"></i>
                                </a>
                                {% endif %}
                            </td>
                        </tr>
                        {% endif %}
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <a href="{% url 'products:index' %}" class="btn btn-a btn-round form-control  my-2 last">
                продолжить покупки
            </a>
        </div>
    </div>
</div>
{% endblock %}